### ISSUE TITLE
Media library timeout is always 10.000

### ISSUE THREAD

**Issue by eyadsibai** [mopidy/mopidy-spotify#129]
if I modify the timeout in the config this is not being reflected. still I get timeout after 10 secs when I try to load the media library for example.

**Comment by kingosticks** [comment]
We only seem to use the configured timeout for loading a track before we try and play it. Every other use of `load` is called with no arguments and hence uses pyspotify's default timeout of 10 seconds. 

Lots of people do hit this but it's usually a sign that sometime else is wrong (i.e. something at Spotify's end) since a 10 second timeout is really quite long. But we should fix it, good spot.

**Comment by jaedb** [comment]
A good example of a genuine use case where 10s is not enough is when we want to play a playlist URI. 10 seconds would suffice for getting single objects, but a playlist lookup may be 100+ tracks.

For example: https://github.com/jaedb/Iris/issues/36

**Comment by eyadsibai** [comment]
spotify-mopidy

**Comment by oblitum** [comment]
Can't browse and play any playlist from Genres and Mods, always timing out.

**Comment by oblitum** [comment]
Well, even after applying #139, no luck trying to browse Genres & Moods playlists...

**Comment by kingosticks** [comment]
@oblitum you are seeing https://github.com/mopidy/mopidy-spotify/issues/133

**Comment by jodal** [comment]
Fixed by PR #139.
