### ISSUE TITLE
invalid_client when using client_id/client_secret keys

### ISSUE THREAD

**Issue by jaedb** [mopidy/mopidy-spotify#145]
When using the credentials generated by (Mopidy)[https://www.mopidy.com/authenticate/#spotify], I receive an `invalid_client` error. I'm testing this outside of Mopidy-Spotify using the steps outlined in the Spotify documentation [Client Credentials flow](https://developer.spotify.com/web-api/authorization-guide/#client_credentials_flow)

When I use the `client_id` and `client_secret` tokens generated from a separate Spotify Application (eg _My Applications_) these work fine. Do these token types differ somehow?

**Comment by adamcik** [comment]
https://www.mopidy.com/authenticate/ uses an auth bridge running https://github.com/adamcik/oauthclientbridge This is done so we can keep the application secret secret. `mopidy-spotify-web` has code for supporting you setting up your own app instead of using our bridge, but we've not implemented that for this plugin.

**Comment by jaedb** [comment]
A belated response; is it possible to use your credentials within _Iris_?

**Comment by adamcik** [comment]
Should work just fine, but there are some caveats.

You just need to use https://auth.mopidy.com/spotify/token for getting auth tokens and `grant_type=client_credentials` then simply use basic auth or `client_id` and `client_secret` in the post data.

This assumes that you just grab to config keys from the spotify config inside your extension. As we don't have a way to give anyone outside this plugin the current usable token. I don't think having two active tokens should matter much.

I do however have to ask that you try and be careful with retries, the client bridge does have per IP and client id rate limits to protect our Spotify OAuth app from getting in trouble with them. So include a backoff on errors, and give up on permanent errors (instead of retrying harder like mopidy-spotify currently does).

#148 mentions what scopes we currently request, but there is a chance that older token won't have all of these as we used to request less. So you need check that the token you fetch gets the scopes you need.

```
curl --data "grant_type=client_credentials&client_id=my-id&client_secret=s3cret" https://auth.mopidy.com/spotify/token                                          
```

**Comment by jaedb** [comment]
Great, thanks for this extra insight into how this works. I think this will be a better way to get the initial Spotify access up and running. Currently I use the username/password from `[spotify]` and manually get another token.

The end user will still need to authorize using the _Authorization Code Flow_ for those manipulative functions (like unfollowing tracks, etc) though.

**Comment by adamcik** [comment]
Are there any scopes you need that are missing? `user-library-modify` and `user-follow-modify` perhaps?

Currently I've tried to add everything we envision supporting from https://developer.spotify.com/web-api/using-scopes/ - though just noticed `playlist-modify-public` isn't in there, not sure if that is new or even needed when we have private already. `playlist-read-collaborative` also looks new to me.

```
OAUTH_SCOPES = [
    'playlist-modify-private',
    'playlist-read-private',
    'playlist-read-collaborative',
    'user-follow-read',
    'user-library-read',
    'user-read-recently-played',
    'user-read-private',
    'user-top-read',
]
```

We could probably add anything reasonable. I just wanted to not add more than we realistically need.

**Comment by jaedb** [comment]
The only ones Iris currently uses that you're not are:
```
'playlist-modify-public',
'playlist-modify-private',
'user-library-modify',
'user-follow-modify'
```

What are your thoughts around using _Authorization Code Flow_ instead of the _Client Credentials Flow_? Would this not have the benefit of granting additional access to the backend plugins? Then you'd be able to call Spotify directly for fresh tokens, rather than having to call back to your OAuth bridge.

I've tinkered with the Spotify authentication flows a fair bit, but I'm still figuring it out!

**Comment by adamcik** [comment]
The main reason for using the client flow and going via the bridge is avoiding the two following scenarios:

- The OAuth secret from Spotify getting shared as it would need to be in the extension, and both Spotify and the OAuth RFC say this should be kept secret.
- Every user having to register their own OAuth app if we don't distribute a secrete.

**Comment by jaedb** [comment]
I've got this integrated now and it's working beautifully! Any manipulation of following states will still require _Authorization Code Flow_, but by using the your OAuth bridge we've enabled users more functionality = win.

Do you think it's viable to add those additional authorization scopes to your OAuth bridge?
