### ISSUE TITLE
Lazy initialization to speed up startup time and performance on Raspberry PI

### ISSUE THREAD

**Issue by BlackLight** [mopidy/mopidy-spotify#151]
I've got a Spotify library with a bunch of thousands of artists and tracks.

That means that mopidy spends a lot of time (~ 10/15 minutes) to pre-load and populate the artists/tracks hierarchies (Rasberry Pi 3 running Arch), and even when it's done every basic operation times out.

How hard would it be to implement some kind of "lazy fetch" mechanism? Or even entirely skipping the artists/tracks population as an option. I don't mind to just play my Spotify playlists on my RPi and do a regular search if I want something more, as long as it gets at least usable.

**Comment by kingosticks** [comment]
When you say library , you are you talking about playlists rather than  'My Music', right? (libspotify has no support for 'My Music'). libspotify should be caching the artist and track data for your playlists so there shouldn't be much network activity during this time, is that what you observe? Have you tried playing with the cache settings?

libspotify has a `initially_unload_playlists` config setting (which pyspotify exposes), but IIRC once you access any of your playiists it'll start trying to load all your playlist data into memory. If it doesn't have the data cached it'll fetch it over the network. To avoid that I *think* you'd have to disable playlists in mopidy-spotify entirely. We are currently moving to using the Web API rather than libspotify for stuff like this so we may have greater control of this kind of thing in future.

But ignoring the 15 min loading for now, once it's all loaded it shouldn't be timing out. Are you using an MPD or HTTP client?

**Comment by BlackLight** [comment]
Seems like allow_cache was still disabled by default for some reason.
allow_cache = true significantly improved the performance, after the first slow start of course.
Will re-open the issue in case I see further performance degradations.

Fabio

**Comment by kingosticks** [comment]
But, just to check, had you changed `allow_cache`? It should be enabled by default.
