### ISSUE TITLE
Spotify Search started to return no results

### ISSUE THREAD

**Issue by offwhite** [mopidy/mopidy-spotify#167]
Running the pi music box and mopidy-spotify was working as expected until yesterday when search started to return no results. Where as this command worked before:

`curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.library.search" , "params": {"any": "Nick Cave", "uris": ["spotify:"]}}' http://musicbox:6680/mopidy/rpc`

It now returns:

`{"jsonrpc": "2.0", "id": 1, "result": [{"__model__": "SearchResult", "uri": "spotify:search:Nick%20Cave"}]}`

All other spotify functions work as before. Any more changes to the spotify api? Anyone else getting this problem?

**Comment by kingosticks** [comment]
Pi Musicbox uses an old version of mopidy-spotify (v1.4.0) which is no longer supported here. This is not an issue in the current version of mopidy-spotify. 

I can confirm it is a problem in v1.4.0 since yesterday. Spotify routinely break it, and so far they have always _eventually_ fixed it although that is not guaranteed to happen again. I work on fixing pimusicbox.
