### ISSUE TITLE
Question - serrvice connection

### ISSUE THREAD

**Issue by adfaure** [mopidy/mopidy-spotify#177]
Hello, 
yesterday I tried to install modipy-spotify. I filled the configuration
with my credentials, but whenever I run the web app, I still need to 
manually connect to a service on the web GUI. It works, but isn't it supposed to
connect using my credentials ? So i am posting this issue because somehow it works, but 
I am not sure I is supposed to work that way.

Sorry for the inconvenience.

**Comment by kingosticks** [comment]
Please ask usage questions at https://discourse.mopidy.com

And when you post there be sure to include information about what webclient you are using since this doesn't sound like an issue with mopidy-spotify itself. Also include what exactly you are doing and what you expect to happen since this question is currently too vague. Thanks
