### ISSUE TITLE
Spotify + facebook account = ErrorType.BAD_USERNAME_OR_PASSWORD: 6

### ISSUE THREAD

**Issue by metalelf0** [mopidy/mopidy-spotify#179]
So, this is the error message I get:

```
ERROR    Spotify login error: <ErrorType.BAD_USERNAME_OR_PASSWORD: 6>
```

What I did:
* installed `mopidy` and `mopidy-spotify` from the deb repository via apt (last version);
* got the client_id and client_secret successfully;
* visited the spotify settings to get the 10-digit login;
* clicked on the "Send email to reset password" button, got the error message;
* went to facebook settings -> security and login -> app passwords, clicked "generate app passwords", entered "Spotify" and clicked generate;
* entered settings in `~/.config/mopidy/mopidy.conf` under `[spotify]`;
* started mopidy.

I'm on Ubuntu 18.04.

What I noticed:
* regenerating client_id and client_secret gives different values every time (but maybe this is correct);
* the username and password don't contain any special character (they are both digit sequences);
* also tried entering "spotify" (without the capital "S") in the facebook app password settings, still got the same problem.

Maybe I'm missing something obvious...

Thanks, keep up the great work!

**Comment by aeikenberry** [comment]
I'm also having trouble logging in where my Spotify is linked to my Facebook account. I used mopidy with this account years ago and was able to get it to work with my userid/facebook password. I tried to use this again and can't get it to work. I tried using my facebook password, made a 'device password' in Spotify, as well as an 'App Password' in Facebook itself, and none of those worked. Any tips?

**Comment by Beny406** [comment]
Same problem for me. I am not sure if I should use my email as username or appname I inputed during password generation on facebook. I have tried both, none of them work giving the same error you described.

**Comment by midnightmastermind** [comment]
Was this ever solved?

**Comment by metalelf0** [comment]
I contacted the Spotify support team to migrate to a non-facebook-login account. Unfortunately this seems to be the only way to get many Spotify integrations working.

**Comment by Kkoile** [comment]
Hi all,

I have the same problem as described above. Unfortunately it does not work to set the device password through spotify, because I don't have access to the registered Email Adress anymore and there seems to be no way of changing the email address.
Has anyone figured out how to connect to Spotify with an account authorized by facebook? After I create an app password in facebook, should I be able to login in the web interface with my Spotify username (10 digits) and the generated password? I always receive an HTTP Code 400 and the interface is not responding at all to my login attempt. 
Another question: Is the name relevant I use to create the app password in facebook? If so, what name should I use? I tried `Spotify`, `spotify`, `Mopidy-Spotify`...

Thanks for your help

**Comment by kingosticks** [comment]
Have a go at the things discussed at:
* https://robblewis.me/convert-spotify-facebook-to-email-login/index.html
* https://news.ycombinator.com/item?id=18212383

Or contact Spotify support and get them to sort it out for you. Please let us know what worked.
