### ISSUE TITLE
Spotify Playlist Status

### ISSUE THREAD

**Issue by DylanCDuke** [mopidy/mopidy-spotify#216]
Hello!

Relatively new to pi and in turn mopidy. 

I've seen a lot of back and forth on this topic in the last few weeks (broken, fixed, etc). I do see #188 in the readme was suppose to resolve this via a webapi. I'm not sure how to use this webapi - or instructions in the topic on how to download a package that's required or anything similar. 

1) Are these still broken?
2) Is there a workaround?

I'm currently using a pi with musicbox which is (obviously) based on mopidy - with both web clients.

**Comment by giltwist** [comment]
My workaround was to install [Spotifyd](https://github.com/Spotifyd/spotifyd) on the pi to convince Spotify that it was a smart speaker.   However, I don't think mopidy-spotify can take that route because they want to use the official API.

Do note that the installation directions for Spotifyd put all the config files in the user folder rather than the system service folder.  You'll have to do some tinkering to make it work as a service without a user logged in like Mopidy does.

**Comment by kingosticks** [comment]
The status on the readme is still accurate. It'll get updated when something changes.

**Comment by kingosticks** [comment]
But I wil add that pimusicbox is unfortunately a bit more complicated again. There's no workaround other than to use the Spotify connect functionality rather than the Web ui. If you have any specific pimusicbox questions please post them on the section of discuss.
