### ISSUE TITLE
mopidy-spotify is not listed in apt-get

### ISSUE THREAD

**Issue by LennartHennigs** [mopidy/mopidy-spotify#232]
Hey, 
I just tried to install mopidy-spotify on Raspian but I get the following error...

`E: Unable to locate package mopidy-spotify`

Any alternatives to install it on Raspian?
Cheers
l.

**Comment by jodal** [comment]
Mopidy-Spotify isn't a part of Debian/Raspbian because of the licensing of closed-source libspotify, which it depends on. It might have been possible to get libspotify into the non-free suite in Debian, but given that libspotify has been deprecated for a long time, that'll probably never happen.

However, Mopidy-Spotify and all of its dependencies are available as Debian packages from https://apt.mopidy.com.

**Comment by LennartHennigs** [comment]
I see, thanks!
For people with similar issues, I used this how-to: https://docs.mopidy.com/en/latest/installation/debian/

...using these commands:
```
$ wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
$ sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list
```

This worked flawlessly.
(You might consider updating the README, then, to reflect the changes.)

Cheers
l.

**Comment by kingosticks** [comment]
@LennartHennigs what do you mean "changes"? The README looks correct, what am I missing?

**Comment by kingosticks** [comment]
I've added something. If you think it could be further improved please make a suggestion. 

FYI, if you were not already using apt.mpoidy.com you probably don't have the latest version of Mopidy. Raspbian's APT repositories quickly go stale.

**Comment by LennartHennigs** [comment]
Cool. And Thanks! 
After adding _apt.mopidiy_ mopidy was updated because of the newer packages it found there.
