### ISSUE TITLE
Multiple Spotify Accounts

### ISSUE THREAD

**Issue by bbalazs** [mopidy/mopidy-spotify#263]
What would I have to do in order to feed multiple instances of Spotify into mopidy? So, every user can feed and listen to their own spotify account? I want to achieve something like [https://www.home-assistant.io/blog/2016/02/18/multi-room-audio-with-snapcast/](url)

**Comment by kingosticks** [comment]
By far the simplest thing would be run multiple instances of the entire Mopidy server, each logged into its own instance. Feed each separate instances into snapcast. If your question is how to achieve that then ask in the user forum. 

Having multiple instances of a particular extension with Mopidy is not supported, but maybe you could hack that up. Supporting different Spotify logins at the same time, or swapping between logins, would take a substantial amount of work.

**Comment by peakyy15-tech** [comment]
Spotify Premium elevates the listening experience with crystal-clear audio and complete freedom from ads. It’s crafted for users who value uninterrupted music, personalized playlists, and seamless playback across devices. [Spotify Premium Apk](https://www.spotifull.com/) subscribers can download tracks for offline listening, switch between songs instantly, and enjoy a consistent, high-quality sound anywhere. By choosing the official service instead of unauthorized alternatives, users gain access to reliable performance, continuous updates, and a secure platform that directly supports their favorite artists and creators.
