### ISSUE TITLE
When playing through mopidy-spotify, spotify thinks I'm on my phone

### ISSUE THREAD

**Issue by majuscule** [mopidy/mopidy-spotify#265]
Problem is, despite it thinking I'm on my phone, my phone *doesn't* think I'm on my phone (because I'm not). This means I can't use my phone as a remote control through spotify. I could work around this by using mopidy properly (setting up a server and using an mpd client on my phone), but I'd really rather not.

To reproduce:

Play music through mopidy-spotify (I am using ncmpcpp if that makes any difference but I doubt it?)
Log into spotify on your phone.
Play a song - it plays on my phone.
Turn that off because it's annoying.
Log into the open.spotify.com web player and select "connect to a device" in the lower right.
A popup will appear: "Listening on Pixel 4".

Additional notes: If I force kill spotify on my phone and reload the browser, it no longer reports *any* devices playing, despite mopidy-spotify still playing.

I'm very confused about what's going on here.

**Comment by kingosticks** [comment]
Mopidy-Spotify does not support Spotify Connect in any way. Reporting of playback status on other devices is part of Spotify connect. What should be happening is that when you start playing Spotify on your phone, mopidy-spotify playback should *pause* because they should be enforcing the rule of only one playback device at a time (not part of Connect). Is that not happening? What do you think should be happening, keeping in mind there is no support for Spotify Connect?

**Comment by kingosticks** [comment]
@majuscule are you still having a problem here?

**Comment by kingosticks** [comment]
No reaponse and this will change with the merge of https://github.com/mopidy/mopidy-spotify/pull/342
