### ISSUE TITLE
API rate limit exceeded when trying to lookup anything

### ISSUE THREAD

**Issue by Kamefrede** [mopidy/mopidy-spotify#266]
After a fresh install of Arch I installed mopidy and mopidy-spotify and managed to get it configured properly.
Now, 10 days later whenever I try to search for something it comes up with no results found.
Journalctl shows that the searches error out with error code 429 ( API rate limit exceeded).
Is there any fix for this?

**Comment by kingosticks** [comment]
@adamcik / @jodal can someone check what's going on with our account?

**Comment by kingosticks** [comment]
Although, I can't reproduce this. Searching (and everything else) is working fine here.

**Comment by adamcik** [comment]
Some older mopidy-spotify versions can go into a retry loop for auth, in which case the oauth service we run will probably give you 429. This typically only happens if you misconfigure something.

Could you provide the version of mopidy spotify, and the logs so we can see if this is us giving you a 429 during auth, or spotify doing something when you talk to their API after auth is completed.

**Comment by Kamefrede** [comment]
> Some older mopidy-spotify versions can go into a retry loop for auth, in which case the oauth service we run will probably give you 429. This typically only happens if you misconfigure something.
> 
> Could you provide the version of mopidy spotify, and the logs so we can see if this is us giving you a 429 during auth, or spotify doing something when you talk to their API after auth is completed.

I had indeed an old mopidy-spotify version! 
Unsure as to what version it was but now I'm running mopidy-spotify 4.0.1-1
Probably should've tried and update before posting the issue, sorry!
