### ISSUE TITLE
Using Spotify, I can stream with two different devices

### ISSUE THREAD

**Issue by busybox11** [mopidy/mopidy-spotify#275]
Let me explain the situation here.
I'm currently streaming music on my phone.
I just installed Mopidy and Iris with Spotify, tried playing music, and now I have two different devices playing different music.

Why is this a thing? I think it's because Spotify Connect isn't a thing here but I don't really know.

**Comment by busybox11** [comment]
I'm not sure if this is the right repo, tho.

**Comment by busybox11** [comment]
Oh, and it has the same behavior with MPD.

**Comment by scorgn** [comment]
This is what confuses me. I understand Spotify connect is not supported, but the fact that you can stream from multiple devices simultaneously when that's specifically/intentionally restricted from Spotify is odd to me.

**Comment by jodal** [comment]
Playing music with Mopidy-Spotify Will normally cause a Spotify stream on another device using the same account to stop. It also works the other way around, playing music elsewhere will cause Mopidy-Spotify to pause. This behavior predates Spotify Connect with several years, so that should not be relevant.

If you don't observe this behavior I suspect that the other device might be playing in offline mode, so Spotify doesn't know about it?

Either way, this restriction applies to Mopidy-Spotify just like most, if not all, other Spotify clients. We don't have any logic related to this, as it is all handled inside the libspotify library and Spotify's servers.

**Comment by scorgn** [comment]
Right, that's what I thought. But what was confusing to me is that I'm able to stream from two different streams, actively choosing new songs that are definitely not accessible from offline mode.

I just tried now to confirm, searched "Something" through Spotify and found two songs I had never heard of before. I played one through Mopidy-Spotify and the other through Spotify. Then continued to switch the songs to other new songs on both my computer and Mopidy-Spotify. Neither of the streams were disconnected.

I'm not protesting closing the issue or anything, there's no real issue with Mopidy-Spotify, but it is definitely odd to me.
