### ISSUE TITLE
Liked tracks

### ISSUE THREAD

**Issue by winterscar** [mopidy/mopidy-spotify#297]
The main way I use Spotify is to navigate to my "Liked Tracks" and hit "Play All".
I use this library in association with home-assistant, and I can start playing any of my playlists without problems, but I'm unable to figure out how I might instruct mopidy to just shuffle all my "Liked Tracks" from spotify.

Is this possible using this library?

Thanks.

**Comment by jodal** [comment]
For all music backends, Mopidy supports both:
- physically shuffling the play queue (called the "tracklist") so that you can view what order the tracks will be played in,
- "random" play mode, where it will pick the next song by random.

I'm not familiar with the HomeAssistant Mopidy integration, so I don't know if or how this functionality is exposed there. Please try asking at https://discourse.mopidy.com or the maintainers of the HomeAssistant integration.

**Comment by winterscar** [comment]
Hi, thanks for clarifying about the shuffle modes mopidy supports. However, my question was more around how I can get my "liked songs" from spotify into the tracklist in the first place.

**Comment by jodal** [comment]
AFAIK we don't expose "Liked Songs" in any way, and I can't immediately find any support for them in [Spotify's Web API](https://developer.spotify.com/documentation/web-api/reference/). If anyone can point out my error or if Spotify adds support for it to the Spotify Web API, we can make "Liked Songs" available in Mopidy-Spotify too.

**Comment by winterscar** [comment]
Would it not be this?
https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-users-saved-tracks

**Comment by djmattyg007** [comment]
I think @winterscar is referring to the "folders" presented through the `browse` integration, by navigating to Spotify -> Your music -> Your Tracks. This isn't a playlist and therefore presumably can't be triggered through an integration that only supports playlists.

It might be possible to provide a fake "liked tracks" playlist?

**Comment by winterscar** [comment]
That seems like a good solution to me!

**Comment by djmattyg007** [comment]
@winterscar Would you be able to take a look at #313 and see if it resolves your issue?
