### ISSUE TITLE
Cannot make a new authentication

### ISSUE THREAD

**Issue by thiderman** [mopidy/mopidy-spotify#317]
I'm trying to grant the API access to the app. The popup shows up, and I can complete the flow and grant the access. But, as soon as it shows up, there's an error that says `Popup closed without completing authentication.`

In the console, the following error is printed;

```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://auth.mopidy.com’) does not match the recipient window’s origin (‘https://mopidy.com’).
```
I'm fairly certain that's a misconfiguration and not an error on my part. Am I wrong and is there something I can do and/or am doing wrong? FWIW, I've disabled any privacy/adblocker add-on that could interfere with this.

**Comment by jodal** [comment]
@adamcik Could you have a look at this one?

**Comment by adamcik** [comment]
Without info about the browser version etc I can't really attempt to reproduce. Whatever you are running seems to be more strict that what we've tested with before.

As a workaround try a different browser.

I'll see about adding some fallback that just spits out things in the pop-up instead of closing itself in the rare case that this doesn't work.

Thanks for the report.

**Comment by thiderman** [comment]
I'm fairly certain I tried in incognito yesterday, but since I wasn't sure I tried again. And, lo and behold - it worked now. I feel stupid. :sweat_smile:  

Apologies for the noise!
