### ISSUE TITLE
mopidy spotify not working due to libfii.so.8 update

### ISSUE THREAD

**Issue by nautilor** [mopidy/mopidy-spotify#322]
after a system update which changed libffi from version 7 to 8 I cannot use mopidy-spotify cause I get this error message:

```ImportError: libffi.so.7: cannot open shared object file: No such file or directory```

In my system I have
```
% locate libffi.so.8                                                                                
/usr/lib/libffi.so.8
/usr/lib/libffi.so.8.1.0
```

**Comment by trygveaa** [comment]
When libffi is upgraded to a new major version you have to recompile the python cffi library so it uses the new version instead of trying to use the old. If this is necessary to do manually and how to do it depends on how you installed it. Since you're running into this problem, I assume you have installed it with pip (or installed pyspotify/mopidy-spotify with pip, which would pull it in as a dependency). Not sure the exact command for this, maybe `pip install --upgrade cffi` or `pip install --force-reinstall cffi`.

**Comment by VGsNETWORK-Utility** [comment]
Ok, seems that running `pip install --upgrade cffi` solved the problem.

**Comment by nautilor** [comment]
Ok, running `pip install --upgrade cffi` solved the problem.

Thanks
