### ISSUE TITLE
Please remove this extension from the Mopidy extension directory

### ISSUE THREAD

**Issue by chrismetcalf** [mopidy/mopidy-spotify#384]
It appears that this extension is broken and there is no plan to fix it: https://discourse.mopidy.com/t/spotify-login-error-errortype-user-needs-premium-15/5459/19

I just sunk a bunch of time into building out a Raspberry Pi for Mopidy, only to discover that one my primary use cases (streaming music from Spotify) didn't work when I sunk yet more time into diagnosing errors from Spotify extension. 

If the plugin does not work and will not be fixed, please remove it from the extension directory or at least post a warning.

**Comment by kingosticks** [comment]
Forgive the obvious question but I'm a little confused: did you read the [README](https://github.com/mopidy/mopidy-spotify/blob/main/README.rst)?

**Comment by chrismetcalf** [comment]
The readme does state that some features are unavailable, but still lists the following as working:

```Working support for the following features is currently available:

- Playback
- Search
- Playlists (read-only)
- Top lists and Your Music (read-only)
- Lookup by URI```

Even the basic stuff like playback appears to be broken as of May 2022, ever since libspotify was sunsetted: https://discourse.mopidy.com/t/spotify-login-error-errortype-user-needs-premium-15/5459/5

**Comment by chrismetcalf** [comment]
OK, my apologies. I had an old broken version of the extension installed from apt, and when I stepped through the instructions to manually install the correct version from pip it works now!

I'll shamefully close my own ticket... 😅

**Comment by kingosticks** [comment]
Yes. those feature all work if you follow the instructions to install the new dependency and the latest working alpha release. Apologies but I can't make the old version work again, you do need to install the new alpha version. 

Thanks for pointing out that old thread never got an update. I have since [posted an update](https://discourse.mopidy.com/t/spotify-login-error-errortype-user-needs-premium-15/5459/35) there to hopefully clarify the current status.
