### ISSUE TITLE
Add Autoplay after Startup

### ISSUE THREAD

**Issue by Baebeca** [mopidy/mopidy-spotify#43]
Add an Option to start the first entry vom specific playlist after startup server

**Comment by adamcik** [comment]
This has already been requested as https://github.com/mopidy/mopidy/pull/181 - the plan has since been to solve this with https://github.com/mopidy/mopidy/issues/310 and possibly some extra flags/config options.

Closing this as it can't be fixed in mopidy-spotify and needs to be added to mopidy itself.

**Comment by Baebeca** [comment]
thx!
