### ISSUE TITLE
Search is returning unavailable tracks

### ISSUE THREAD

**Issue by crgpww** [mopidy/mopidy-spotify#97]
With the migration to the spotify web api, the search results contains tracks that are not available in the user's country.

I found the @trygveaa comment on #94 about this, but we need a way to specify the desired market as a parameter or at least have the 'available_markets' array on the track/album returned object so we can filter it later. 

An exemple, as I'm living in Brazil (BR), https://api.spotify.com/v1/search?q=%22Menina+da+saia+verde%22&type=album%2Cartist%2Ctrack&limit=50

**Comment by trygveaa** [comment]
I can think of three possible solutions to this (well, one of them I'm not sure if is possible, and that's the only one I like...):

1. Add a new config option for specifying the market you want.
2. Add login for the Web API, so we can use the users market. This is tricky, since the login method is completely different than for libspotify, and it would complicate config for users.
3. Get the users market from libspotify. This is my preferred option, but I don't know if it is possible. @jodal: Do you know if this info is available from libspotify?

**Comment by jodal** [comment]
No, I don't think that is available through libspotify. You can get toplists for the region of the current user, but there's nothing telling you what region that is.

**Comment by kingosticks** [comment]
4. Filter the track results using `track.availability` ?

**Comment by kingosticks** [comment]
Actually, cancel that, availability is seemingly for online/offline availability and not what I first thought.

**Comment by wiibaker** [comment]
I created a simple pull request #109 to add the market into the search query if it is specified. I do not have proper Python environment to compile/build/test the code, but the code is simple enough do such a change "blid". Some tweaks might be needed though. Please, check if you find it usefull.

**Comment by kingosticks** [comment]
I'm not sure how we missed it before... but libspotify does have [sp_session_user_country](https://developer.spotify.com/docs/libspotify/12.1.51/group__session.html#ga54c7693afa9be664f3ea870feb0df8d9)!
